[package]
name = "arctic-downloader-tauri"
version = "0.2.9"
edition = "2021"
rust-version = "1.89"
authors = ["Arctic Latent"]
license = "Apache-2.0"

[[bin]]
name = "Arctic-ComfyUI-Helper"
path = "src/main.rs"

[package.metadata]

[features]
default = ["desktop-tray"]
desktop-tray = ["tauri/tray-icon"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
anyhow.workspace = true
env_logger.workspace = true
fs2 = "0.4"
log.workspace = true
open.workspace = true
rfd.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tauri = { version = "2", features = ["image-png", "image-ico"] }
tokio = { workspace = true, features = ["rt"] }
tokio-util = { workspace = true, features = ["rt"] }
reqwest = { workspace = true, features = ["blocking", "json", "rustls-tls"] }
arctic-downloader = { path = ".." }
tauri-plugin-single-instance = "2"
tauri-plugin-notification = "2"

[target.'cfg(target_os = "linux")'.dependencies]
glib = "0.18"

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_JobObjects",
] }
